SELECT DISTINCT( A.EMPLID, A.CAMPUS_ID,
    B.NAME_DISPLAY "NAME",
    C.ACAD_PROG "COURSE",
    SUBSTR(C.ACAD_PROG,4,2) "BRANCH",
    E.NAME "FATHER/MOTHER" ,
   
    (  SELECT SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_TERM LIKE '%' AND H.LINE_AMT>'0' AND H.LINE_ACTION != 'REF') AS "TOTAL FEE PAYABLE",         
 
        ( SELECT SUM(G.ITEM_AMT) FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%' AND G.ITEM_AMT>'0' AND G.ACCOUNT_NBR='TUITION001') AS "COURSE FEE APPLIED",
 
          ( SELECT SUM(G.applied_amt) FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%'  AND G.ACCOUNT_NBR='TUITION001') AS "COURSE FEES PAID",
 
          (SELECT SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_NBR='HOSTEL001' AND H.ACCOUNT_TERM LIKE '%' AND H.LINE_ACTION != 'REF' AND H.LINE_AMT>0) AS "HOSTEL FEE PAID",
           
           NVL((SELECT G.ITEM_AMT  FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%' AND G.ITEM_AMT>'0' AND G.ACCOUNT_NBR='BUS001'),0) AS "BUS FEE PAID",
           
           (SELECT (SELECT SUM(G.applied_amt) FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%'  AND G.ACCOUNT_NBR='TUITION001') 
        +
        NVL((SELECT SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_NBR='HOSTEL001' AND H.ACCOUNT_TERM LIKE '%' AND H.LINE_ACTION != 'REF' AND H.LINE_AMT>0),0)
        +
       NVL((SELECT G.ITEM_AMT  FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%' AND G.ITEM_AMT>'0' AND G.ACCOUNT_NBR='BUS001'),0)
         FROM DUAL) AS "TOTAL FEE PAID",
           
           ( SELECT  (SELECT SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_TERM LIKE '%' AND H.LINE_AMT>'0' AND H.LINE_ACTION != 'REF') 
        -
        (
        (SELECT SUM(G.applied_amt) FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%'  AND G.ACCOUNT_NBR='TUITION001') 
        +
        NVL((SELECT SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_NBR='HOSTEL001' AND H.ACCOUNT_TERM LIKE '%' AND H.LINE_ACTION != 'REF' AND H.LINE_AMT>0),0)
        +
       NVL((SELECT G.ITEM_AMT  FROM PS_ITEM_SF_VW G WHERE G.EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%' AND G.ITEM_AMT>0 AND G.ACCOUNT_NBR='BUS001'),0)
       )  FROM DUAL)AS "TOTAL BALANCE",
       
      (SELECT 
      CASE WHEN  (SELECT SUM(G.ITEM_AMT) "TOTAL FEE PAYABLE" FROM PS_ITEM_SF_VW G WHERE EMPLID=A.EMPLID AND G.ACCOUNT_TERM LIKE '%' AND G.ITEM_AMT>0)
       -
        (SELECT SUM(J.ACCOUNT_BALANCE) FROM PS_ACCOUNT_VW J WHERE J.EMPLID=A.EMPLID AND J.ACCOUNT_TERM LIKE '%')<='0'
          THEN 'FULL'ELSE 'NOT FULL' END AS PAYMENT FROM DUAL) AS PAYMENT,
           
     F.ABSENCE_DATE "DUE DATE"
               
  FROM PS_stdnt_srch A,
    PS_HCR_PERSON_NM_I B,
    PS_ACAD_PROG C,
    PS_RELATIONSHIPS E,
   PS_SRMU_SNTFER_TBL F,
    PS_ITEM_SF_VW G,
    PS_ITEM_LINE_VW H,
    PS_CSH_OFF_RCPT_VW I,
    PS_ACCOUNT_VW J
    
    
  WHERE A.EMPLID=B.EMPLID
  AND A.EMPLID  =C.EMPLID
  AND A.EMPLID  =E.EMPLID
  AND A.EMPLID  =F.EMPLID
  AND A.EMPLID  =G.EMPLID
  AND A.EMPLID  =H.EMPLID
  AND A.EMPLID  =I.EMPLID
  AND A.EMPLID  =J.EMPLID;)





SELECT * FROM PS_stdnt_srch A ORDER BY EMPLID  ;
SELECT * FROM PS_HCR_PERSON_NM_I B  ORDER BY EMPLID  ;
SELECT * FROM PS_ACAD_PROG C ORDER BY EMPLID  ;
SELECT * FROM  PS_RELATIONSHIPS E ORDER BY EMPLID  ;
SELECT * FROM  PS_SRMU_SNTFER_TBL F ORDER BY EMPLID  ;
SELECT * FROM  PS_ITEM_SF_VW G ORDER BY EMPLID  ;
SELECT * FROM PS_ITEM_LINE_VW H;
select * from ps_class_roster_vw WHERE  emplid='00000000512';

select * from ps_acad_plan_sf_vw;

--------------
(select EMPLID,ACCOUNT_NBR,case 
WHEN ACCOUNT_NBR='HOSTEL001' THEN 'Y' 
ELSE 'N'
END AS "HOSTEL"
FROM PS_ITEM_SF_VW WHERE EMPLID='00000000001' AND item_term='1201' and account_nbr IN('HOSTEL001'))
UNION
(select EMPLID,ACCOUNT_NBR,case 
WHEN ACCOUNT_NBR='HOSTEL001' THEN 'Y' 
ELSE 'N'
END AS "HOSTEL"
FROM PS_ITEM_SF_VW WHERE EMPLID='00000000001' AND account_nbr NOT IN('HOSTEL001'))
;
-----------
select emplid,SUM(applied_amt), account_nbr, account_term from PS_ITEM_SF_VW where emplid='00000000001' and account_nbr in('HOSTEL001') GROUP BY emplid, account_nbr, account_term ;
-------------

((SELECT SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H WHERE H.EMPLID=A.EMPLID AND  H.LINE_AMT>'0' AND H.LINE_ACTION != 'REF')
   -
   (SELECT SUM(G.APPLIED_AMT) FROM  PS_ITEM_SF_VW G WHERE a.emplid= g.emplid))AS "CURRENT BALANCE "
----------------

----------
SELECT 
(SELECT G.EMPLID,SUM(G.applied_amt) FROM PS_ITEM_SF_VW G,PS_stdnt_srch A WHERE G.EMPLID=A.EMPLID   AND G.ACCOUNT_NBR='TUITION001' GROUP BY EMPLID) , 
         
      ((SELECT sum(G.applied_amt) FROM  PS_ITEM_SF_VW G where G.EMPLID=A.EMPLID AND  G.account_nbr IN('BUS001') )
        union
        (SELECT 0 from PS_ITEM_SF_VW G where G.EMPLID=A.EMPLID AND G.EMPLID NOT in(SELECT DISTINCT G.EMPLID FROM  PS_ITEM_SF_VW G where G.account_nbr IN('BUS001')  )))
        FROM DUAL;
         
---------

--HOSTEL FEE
 ( SELECT H.EMPLID ,SUM(H.LINE_AMT) FROM PS_ITEM_LINE_VW H,PS_stdnt_srch A WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_NBR  IN('BUS001')  
      AND H.LINE_ACTION != 'REF' AND H.LINE_AMT>0 
    group by h.emplid )
    UNION 
    ( select H.EMPLID,0 FROM PS_ITEM_LINE_VW H,PS_stdnt_srch A WHERE H.EMPLID=A.EMPLID AND H.EMPLID 
    NOT IN (SELECT h.emplid FROM PS_ITEM_LINE_VW H,PS_stdnt_srch A WHERE H.EMPLID=A.EMPLID AND H.ACCOUNT_NBR  IN('BUS001')
    AND H.LINE_ACTION != 'REF' AND H.LINE_AMT>0 
    group by h.emplid ) 
    group by h.emplid  ) ;


SELECT * FROM 

------------
SELECT * FROM  PS_ITEM_LINE_VW H where emplid='00000000700'  ; 
SELECT * FROM  PS_CSH_OFF_RCPT_VW I ORDER BY EMPLID  ;
SELECT * FROM   PS_ACCOUNT_VW J ORDER BY EMPLID  ;

SELECT  H.EMPLID,SUM(H.line_amt) FROM  PS_ITEM_LINE_VW H GROUP BY H.EMPLID ORDER BY H.EMPLID  ;

SELECT DISTINCT EMPLID, sel_group FROM  PS_ITEM_SF_VW G ORDER BY EMPLID   ;







--BALANCE
        SELECT  (SELECT SUM(LINE_AMT) FROM PS_ITEM_LINE_VW WHERE EMPLID='00000000001' AND ACCOUNT_TERM LIKE '13%' AND LINE_AMT>'0' AND LINE_ACTION != 'REF') 
        -
        (
        (SELECT SUM(applied_amt) FROM PS_ITEM_SF_VW WHERE EMPLID='00000000001' AND ACCOUNT_TERM LIKE '13%'  AND ACCOUNT_NBR='TUITION001') 
        +
        NVL((SELECT SUM(LINE_AMT) FROM PS_ITEM_LINE_VW WHERE EMPLID='00000000001' AND ACCOUNT_NBR='HOSTEL001' AND ACCOUNT_TERM LIKE '13%' AND LINE_ACTION != 'REF' AND LINE_AMT>0),0)
        +
       NVL((SELECT ITEM_AMT  FROM PS_ITEM_SF_VW WHERE EMPLID='00000000001' AND ACCOUNT_TERM LIKE '13%' AND ITEM_AMT>0 AND ACCOUNT_NBR='BUS001'),0)
       ) AS BALANCE FROM DUAL;
        
  SELECT CASE WHEN (
        (SELECT SUM(H.ITEM_AMT)
        FROM PS_ITEM_SF_VW H,
          PS_CSH_OFF_RCPT_VW I
        WHERE H.EMPLID='00000000157'
        AND H.item_amt>'0'
        GROUP BY H.EMPLID
        ) -
        (SELECT SUM(I.total_amount_sf)
        FROM PS_ITEM_SF_VW H,
          PS_CSH_OFF_RCPT_VW I
        WHERE H.EMPLID='00000000157'
        AND H.item_amt>'0'
        GROUP BY H.EMPLID
        )<='0')  THEN 'FULL' END AS PAYMENT FROM DUAL;
  
 SELECT TOTAL_AMOUNT FROM PS_ANTC_AID_TOT;
 
  --WHERE ((A.ITEM_AMT-B.TOTAL_AMOUNT_SF)<=0)
  --SELECT * FROM PS_ACAD_PLAN;
  --SELECT * FROM PS_SCC_PERS_PHN_H ;
  --SELECT * FROM PS_RELATIONSHIPS;
  SELECT CASE WHEN (SELECT SUM(H.ITEM_AMT)
        FROM PS_ITEM_SF_VW H,
          PS_CSH_OFF_RCPT_VW I
        WHERE H.EMPLID='00000000001'
        AND H.item_amt>'0'
        GROUP BY H.EMPLID)
         -
        (SELECT SUM(I.total_amount_sf)
        FROM PS_ITEM_SF_VW H,
          PS_CSH_OFF_RCPT_VW I
        WHERE H.EMPLID='00000000001'
        AND H.item_amt>'0'
        GROUP BY H.EMPLID)<=0 THEN '0' ELSE 'ABCD' END AS BALANCE FROM DUAL;
        
        --BALANCE
       SELECT SUM(ACCOUNT_BALANCE) FROM PS_ACCOUNT_VW WHERE EMPLID=00000000001 AND ACCOUNT_TERM LIKE '13%';
         SELECT * FROM PS_ACCOUNT_VW WHERE EMPLID=00000000174 AND ACCOUNT_TERM LIKE '12%';
        
          --cOURSE FEE   
   -- SELECT SUM(ITEM_AMT) FROM PS_ITEM_SF_VW WHERE EMPLID=00000000001 AND ACCOUNT_TERM LIKE '13%' AND ITEM_AMT>0 AND ACCOUNT_NBR='TUITION001';
    
    
    --TOTAL FEES(HOSTEL+TUTION)
     SELECT SUM(LINE_AMT) FROM PS_ITEM_LINE_VW WHERE EMPLID=0000000001 AND ACCOUNT_TERM LIKE '13%' AND LINE_AMT>'0' AND LINE_ACTION != 'REF';
     SELECT * FROM PS_ITEM_LINE_VW WHERE EMPLID=0000000001 AND ACCOUNT_TERM LIKE '13%' AND LINE_AMT>'0';
    SELECT LINE_AMT, descr FROM PS_ITEM_LINE_VW WHERE EMPLID=0000000001 AND ACCOUNT_TERM LIKE '13%';
    
   -- SELECT EMPLID,SUM(ITEM_AMT) "TOTAL FEE PAYABLE" FROM PS_ITEM_SF_VW WHERE EMPLID=00000000001 AND ACCOUNT_TERM LIKE '13%' AND ITEM_AMT>0 GROUP BY EMPLID;   
  SELECT ITEM_AMT  FROM PS_ITEM_SF_VW WHERE EMPLID=00000000001 AND ACCOUNT_TERM LIKE '13%' AND ITEM_AMT>0 AND ACCOUNT_NBR='BUS001' ;
  
              --COURSE FEES PAID  
          SELECT SUM(applied_amt) FROM PS_ITEM_SF_VW WHERE EMPLID=00000000001 AND ACCOUNT_TERM LIKE '13%'  AND ACCOUNT_NBR='TUITION001';
         SELECT * FROM PS_ITEM_SF_VW WHERE EMPLID=00000000001 AND ACCOUNT_TERM LIKE '13%';
         
         
         
         
SELECT * FROM PS_ITEM_SF_VW G WHERE EMPLID='00000000700' AND applied_amt>0;
SELECT * FROM PS_ACCOUNT_SF ;

SELECT SUM(G.applied_amt) FROM  PS_ITEM_SF_VW G,PS_stdnt_srch A WHERE  A.EMPLID=G.EMPLID AND G.applied_amt>0 GROUP BY a.emplid ;


SELECT SUM(G.applied_amt) FROM  PS_ITEM_SF_VW G WHERE   G.applied_amt>=0 AND G.account_term like '%3%' GROUP BY g.emplid