SELECT * FROM PS_item_sf_vw X WHERE EMPLID='00000000002';

select * from ps_SRMU_CSH_SUM_VW  WHERE date2 between '13-OCT-13' and '17-OCT-13';

SELECT * FROM PS_DEGREE_TBL;

SELECT * FROM PS_SRMU_CAPSID_TBL;
SELECT * FROM PS_SRMU_ST_DATA_VW WHERE EMPLID='00000000681';
SELECT * FROM PS_SRMU_ST_DATA_VW;

SELECT * FROM ps_SRMU_TUT_INCMVW;

 
 SELECT A.EMPLID 
 , A.NAME 
 , A.NAME_DISPLAY 
 ,A.campus_id
 , B.COUNTRY 
 , B.ADDRESS1 
 , B.ADDRESS2 
 , B.ADDRESS3 
 , B.ADDRESS4 
 , B.CITY 
 , C.PHONE 
 , D.BLOOD_TYPE 
 ,B.POSTAL 
  FROM (((PS_PERSONAL_DATA A LEFT OUTER JOIN PS_ADDRESSES B ON A.EMPLID = B.EMPLID ) LEFT OUTER JOIN PS_PERSONAL_PHONE C ON A.EMPLID = C.EMPLID ) LEFT OUTER JOIN PS_PHYSICAL_EXAM D ON A.EMPLID = D.EMPLID ) 
 WHERE ( B.EFFDT = ( 
 SELECT MAX(B_ED.EFFDT) 
  FROM PS_ADDRESSES B_ED 
 WHERE B.EMPLID = B_ED.EMPLID 
   AND B.ADDRESS_TYPE = B_ED.ADDRESS_TYPE 
   AND B_ED.EFFDT <= SYSDATE) );
   
    
 	
SELECT A.EMPLID, A.ACAD_PROG, A.ADMIT_TERM, A.ACAD_PLAN, A.ACAD_YEAR, A.DESCR, A.ACAD_PLAN_TYPE, A.DEGREE, B.EMPLID, B.NAME_DISPLAY, B.COUNTRY, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.ADDRESS4, B.CITY, B.PHONE, B.BLOOD_TYPE, B.POSTAL, C.PEOPLE_RELATION, C.NAME, D.DESCR, D.YEARS_OF_EDUCATN, B.CAMPUS_ID
  FROM (((PS_SRMU_ST_PLAN_VW A LEFT OUTER JOIN  PS_SRMU_ST_DATA_VW B ON  A.EMPLID = B.EMPLID ) LEFT OUTER JOIN  PS_RELATIONSHIPS C ON  A.EMPLID = C.EMPLID ) LEFT OUTER JOIN  PS_DEGREE_TBL D ON  D.DEGREE = A.DEGREE )
  WHERE ( D.EFFDT =
        (SELECT MAX(D_ED.EFFDT) FROM PS_DEGREE_TBL D_ED
        WHERE D.DEGREE = D_ED.DEGREE
          AND D_ED.EFFDT <= SYSDATE) );
          
          SELECT * FROM PS_SRMU_STU_ID_VW;
 	
  
SELECT DISTINCT A.EMPLID, A.ACAD_PROG, A.ADMIT_TERM, A.ACAD_PLAN, A.ACAD_YEAR, A.DESCR, A.ACAD_PLAN_TYPE, A.DEGREE, B.NAME_DISPLAY, B.COUNTRY, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.ADDRESS4, B.CITY, B.PHONE, B.BLOOD_TYPE, B.POSTAL, C.PEOPLE_RELATION, C.NAME, D.DESCR, D.YEARS_OF_EDUCATN, E.CAMPUS_ID
  FROM ((((PS_SRMU_ST_PLAN_VW A LEFT OUTER JOIN  PS_SRMU_ST_DATA_VW B ON  A.EMPLID = B.EMPLID ) LEFT OUTER JOIN  PS_RELATIONSHIPS C ON  A.EMPLID = C.EMPLID ) LEFT OUTER JOIN  PS_DEGREE_TBL D ON  D.DEGREE = A.DEGREE ) LEFT OUTER JOIN  PS_SRMU_CAPSID_TBL E ON  A.EMPLID = E.EMPLID AND A.ACAD_PLAN = E.ACAD_PLAN )
  WHERE A.EMPLID='00000000681' AND 
  ( D.EFFDT =
        (SELECT MAX(D_ED.EFFDT) FROM PS_DEGREE_TBL D_ED
        WHERE D.DEGREE = D_ED.DEGREE
          AND D_ED.EFFDT <= SYSDATE)
     AND E.EFFDT =
        (SELECT MAX(E_ED.EFFDT) FROM PS_SRMU_CAPSID_TBL E_ED
        WHERE E.EMPLID = E_ED.EMPLID
          AND E_ED.EFFDT <= SYSDATE)
    AND E.EFFSEQ =
        (SELECT MAX(E_ES.EFFSEQ) FROM PS_SRMU_CAPSID_TBL E_ES
        WHERE E.EMPLID = E_ES.EMPLID
          AND E.EFFDT = E_ES.EFFDT) );